loomx.loom_version = "1.16-SNAPSHOT"

mod.id = "ujt_immortal_tamed_pets"
mod.name = "UJT - Immortal Tamed Pets"
mod.group = "org.housearhal"
mod.version = "1.0.0"
mod.channel_tag = ""
mod.description = ""
mod.authors = ["Valerie Arhal"]
mod.contributors = ["Valerie Arhal"]
mod.inception_year = "2025"
mod.license.name = "All Rights Reserved"
mod.license.url = ""
mod.license.dist = "repo"
mod.sources_url = "https://github.com/HouseArhal/UJT-Immortal-Tamed-Pets"
mod.homepage_url = "https://github.com/HouseArhal/UJT-Immortal-Tamed-Pets"
mod.issues_url = "https://github.com/HouseArhal/UJT-Immortal-Tamed-Pets/issues"
mod.discord_url = "https://discord.gg/44fSbYrzZd"
mod.environment = "both"   #"client", "server", "both"
[[mod.pom.developers]]
id = "valeriearhal"
name = "Valerie Arhal"
url = "https://github.com/Valerie-Bosco"

[fabric]
deps.fabric-loader = "0.19.2"

#[fabric."1.19.2"]
#deps.minecraft = "1.19.2"
#deps.fabric-api = "0.77.0+1.19.2"
#deps.modmenu = "4.2.0-beta.2"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.116.7+1.21.1"
deps.modmenu = "11.0.4"

#[fabric."1.21.7"]
#deps.minecraft = "1.21.7"
#deps.fabric-api = "0.128.1+1.21.7"
#deps.modmenu = "15.0.0"
#publish.additionalVersions = ["1.21.6"]
#
#[fabric."26.1.2"]
#deps.minecraft = "26.1.2"
#deps.fabric-api = "0.146.1+26.1.2"
#deps.modmenu = "18.0.0-alpha.8"
#publish.additionalVersions = ["26.1.1", "26.1"]

#[forge]
#
#[forge."1.19.2"]
#deps.minecraft = "1.19.2"
#deps.forge = "43.5.2"

[neoforge]

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.neoforge = "21.1.213"

#[neoforge."1.21.7"]
#deps.minecraft = "1.21.7"
#deps.neoforge = "21.7.1-beta"
#publish.additionalVersions = ["1.21.6"]
#
#[neoforge."26.1.2"]
#deps.minecraft = "26.1.2"
#deps.neoforge = "26.1.2.29-beta"
#publish.additionalVersions = ["26.1.1", "26.1"]
