name: Sync Release Branch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  RELEASE_BRANCH: release

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'

  pull_request:
    branches:
      - main
      - master
    tags:
      - '*'

permissions:
  contents: write


jobs:
  sync-release-branch:
    if: contains(github.head_commit.message, '-sync') || contains(github.head_commit.message, '-release')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "${{env.RELEASE_BRANCH}}"

      - name: Sync release branch from main
        run: |
          git config user.name "${{ github.event.head_commit.author.name }}"
          git config user.email "${{ github.event.head_commit.author.email }}"

          git checkout -B release origin/release
          git reset --hard origin/$DEFAULT_BRANCH
          git push --force-with-lease origin release

  trigger-release:
    if: contains(github.head_commit.message, '-release')

    needs: sync-release-branch
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ github.ref_name }}
